### ISSUE TITLE
If i append args to autostart.opts.appPath the finally generate command is incorrect

### ISSUE THREAD

**Issue by Generalize** [Teamwork/node-auto-launch#116]
```typescript
var appAutoLaunch = new AutoLaunch({ name: 'App',isHidden:true });
appAutoLaunch.isEnabled().then(function (isEnabled){
    if(!isEnabled){
        appAutoLaunch.opts.appPath += ` "${__filename}" "--autostart" `;
        appAutoLaunch.enable();
    }
    console.log(arguments,appAutoLaunch.opts,__filename);
});
``` 
In windows register table added command is "D:\project\vue2\node_modules\electron\dist\electron.exe "D:\project\vue2\desktop.js" "--autostart""
System will treat command arguments as part of executable file path

**Comment by Oxalin** [comment]
Args are not supported in that way. Electron apps use "--process-start-args" before the args that need to be forwarded to the process to be run.

Is your problem specific to the "autostart" in your example or do you want to use other arguments? Because "--autostart" to be the same as the purpose of auto-launch (to add an entry for launch at startup).

Other arguments should be read at process launch from a config/preference file.
