### ISSUE TITLE
After auto launch, the electron default app is getting started first. Then my app is starting

### ISSUE THREAD

**Issue by vaidyaanand** [Teamwork/node-auto-launch#68]
Welcome to Electron

To run your app with Electron, execute the following command under your Console (or Terminal):

path_to_generated path-to-your-app
The path-to-your-app should be the path to your own Electron app, you can read the quick start guide in Electron's docs on how to write one.

Or you can just drag your app here to run it:
- The target platform(s) the problem occurs on (Linux, Mac, Mac App Store, and or Windows): Windows x64
- Node version (run `node -v`): 6.9.0
- auto-launch version: 5.0.1
- The options you're passing to auto-launch: 
- Are you using NW.js or Electron? No
  - If so, which version?
  - If you're using Electron, are you using auto-launch from the main process or a renderer process?
I am using electron
- Can you reproduce this with a simple Hello World example app?
Need to check
- If needs be, would you be able to provide us with a simple app (as simple as possible) which reproduces the problem?

---

**Comment by adam-lynch** [comment]
If I understand correctly, the default Electron app is opened, not your app. This is either because: 

1. You're using an old version of auto-launch which has a bug. So try the latest version (5.0.3).
2. You're opening your app during development and auto-launch is being called. You can't use this module in development. When I'm testing, I run `npm run pack` (see [electron-builder](https://github.com/electron-userland/electron-builder)), then open the generated app. P.S. this module is handy for checking if your app is currently running in development: https://github.com/sindresorhus/electron-is-dev.
