### ISSUE TITLE
Launches electron window when no path specified.

### ISSUE THREAD

**Issue by haykerman** [Teamwork/node-auto-launch#85]
- Platform: Linux: Ubuntu (16.04, 18.04)
- Node: v8.11.3,
- Auto-Launch: v5.0.5
- Options: 'name'
- Electron: v2.0.0
- Process: main
- App Package Type: AppImage

Here is my code snippet
```
const appLauncher = new AutoLaunch({
  'name': 'appname'
});

appLauncher.isEnabled().then((enabled) => {
  if (enabled) return;
  return appLauncher.enable()
}).catch((e) => {
  handleError(e);
});
```

Everything seems to work fine on Windows and Mac, but when logging in Linux (Ubuntu), auto-launch opens an Electron window which says:

> To run a local app, execute the following on the command line: 
> ../../var/www/myprojectname/node_modules/electron/dist/electron path-to-app

**Comment by amits1995** [comment]
I have a similar issue with Appimage but for me the problem is that the created autostart file is refering to a wrong executable. The name of my app is `explorook`, here's the generated autostart file:
```
Type=Application
Version=1.0
Name=explorook
Comment=explorookstartup script
Exec=/tmp/.mount_explortZ7lB5/explorook --hidden
StartupNotify=false
Terminal=false%
```
It looks like Appimage is creating a temp mount folder in which it extracts the executable.  
If we look at the file that Appimage creates in my applications folder (`usr/local/share/applications/appimagekit-explorook.desktop`)
```
[Desktop Entry]
Name=Explorook
Comment=Rookout’s site addon to support local files and folders
Exec="/home/amit/Downloads/explorook-0.0.17-x86_64.AppImage" %U
Terminal=false
Type=Application
Icon=appimagekit-explorook
X-AppImage-Version=0.0.17.49
X-AppImage-BuildId=3a4eed70-82b6-11a8-0ec0-7388b1922ef8
Categories=Utility;
X-Desktop-File-Install-Version=0.23
X-AppImage-Comment=Generated by /tmp/.mount_explorcRyPaG/AppRun
TryExec=/home/amit/Downloads/explorook-0.0.17-x86_64.AppImage
```
I think we auto-launch can detect it runs under appimage via env variables but I think it is more of the app responsibility to pass an custom path to auto-launch  
I will investigate how one can achieve that

**Comment by amits1995** [comment]
Using [$APPIMAGE environment variable](https://github.com/AppImage/AppImageKit/wiki/AppImageKit-components#runtimec) I was able to pull this off. try following this logic:  
```javascript
    let alConfig = { name: "MyAppName", isHidden: true };
    if (process.env.APPIMAGE) {
        alConfig = Object.assign(alConfig, { path: process.env.APPIMAGE })
    }
    const al = new AutoLaunch(alConfig);
```

**Comment by haykerman** [comment]
Thank you, @amits1995. That resolved my issue. I've been struggling to find the right path to executable.
