### ISSUE TITLE
Open two Window (my App and Electron documencation window)

### ISSUE THREAD

**Issue by major697** [Teamwork/node-auto-launch#97]
I have code in main.js in Electron:

```
    let autoLaunch = new AutoLaunch({
        name: 'MyApp',  
        path: process.platform === 'win32' ? app.getPath('exe') : '/Applications/MyApp.app',
    });
    
    autoLaunch.isEnabled().then((isEnabled) => {
        settingUser().then((res) => { 
            if (res.auto_start == 1) {
                if (isEnabled) autoLaunch.enable();
            }else{
                if (isEnabled) autoLaunch.disable();
            }
        });
    });
```

I have problem , because when I start Mac node-auto-launch run two window. First window with my application and second window with documencation Electron. How I can remove/disbale documencation Electron window ?
In Windows 10 documencation Electron window not run.

**Comment by yafp** [comment]
**Wild guessing:** 

Could it be that the unwanted second comes from auto-start you configured while running a non-packages version of the app?

At least for me it looks like if i run my project unpackaged, and create a .desktop file using auto-launch (on linux) for handling the auto-start - it results in an electron.desktop file and not in appname.desktop file

Consider checking your stored launchd files, remove them both, and re-create the auto-launch entry using a packaged version of your app.

**Comment by deanturner** [comment]
did any one find solution for this issue ?
I have same problem and could not resolve yet after reading @yafp comment.

**Comment by sameekshaj** [comment]
if we run our app in our local system, in Linux it creates an electron.desktop file and if we uninstall the app this file remains there. so after running app build we see two windows one is our app and another is an electron default window. For Linux go to this path ~/.config/autostart/ and windows - \HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run this and remove that electron file (which got created after running the app locally because its getting consider as an individual app which has an auto-launch feature)

**Comment by richard457** [comment]
Any solution to this?

**Comment by Oxalin** [comment]
Find the duplicated entry. As explained in https://github.com/Teamwork/node-auto-launch/issues/97#issuecomment-529892436 and https://github.com/Teamwork/node-auto-launch/issues/97#issuecomment-696640615, something must have created a second entry at some point (name of the app was changed, packaged VS unpackaged) that must be deleted.

Not an auto-launch bug.
