### ISSUE TITLE
Invalid .desktop file is created if path contains spaces on Linux

### ISSUE THREAD

**Issue by alexhenrie** [Teamwork/node-auto-launch#99]
If the path contains spaces, e.g. `/opt/IPFS Desktop/ipfs-desktop`, it needs to be quoted in the `Exec` line of the .desktop file. Otherwise the part before the space is interpreted to be the filename and the part after the space is interpreted to be a commandline argument.

**Comment by miyanoshiyo** [comment]
Can you use auto-launch on Linux successfully? I canot work it on linux

**Comment by miyanoshiyo** [comment]
Can you use auto-launch on Linux successfully? I cannot work it on linux

**Comment by phellipeandrade** [comment]
Still relevant!

**Comment by erik-404err** [comment]
Im having the same problem. Manually launching the `.desktop` file i get the error: There was an error launching the application.
If anyone runs into this as well, you can go to `/home/{yourName}/.config/autostart/` and open the `.desktop` file. it should look like this:
```
#!/usr/bin/env xdg-open
[Desktop Entry]
Type=Application
Version=1.0
Name=appName
Comment=appNamestartup script
Exec=/opt/Some Name/appName
StartupNotify=false
Terminal=false
```
you need to change this to:
```
Exec= "/opt/Some Name/appName"
```
this is especially sad for NW.js / electron since:
"`options.path` - String (optional for NW.js and Electron apps)"
~ https://github.com/Teamwork/node-auto-launch/blob/master/README.md

Hope that this helped someone and that this gets fixed soon (because you cant tell everyone installing you app to modify files)

**Comment by joel1st** [comment]
For those looking for a work around that allows you to still use the library:
You explicityly pass in a path if it is an AppImage, and add back slashes before any space characters (which escapes it).
```
  let name = 'Application Name';

  let autoLauncher = new AutoLaunch(
    process.env.APPIMAGE
      ? {
          name: name,
          path: `${process.env.APPIMAGE}`.replace(/ /g, '\\ '),
        }
      : {
          name: name,
        }
  );
```

**Comment by Izurii** [comment]
As the originals developers of the package is not maintaining this project anymore, I replicated and will be taking over, if you could take a look at it I'll be happy. This issue is already solved in my version of the project.

https://github.com/Izurii/easy-auto-launch

**Comment by Oxalin** [comment]
Same as https://github.com/Teamwork/node-auto-launch/issues/78
